name: Print My Name

on:
  push:
    branches:
      - main  # or your default branch
  workflow_dispatch:  # allows manual triggering

jobs:
  print-name:
    runs-on: ubuntu-latest

    steps:
      - name: Print Name
        run: echo "my name is varsha"
